servers=[
      {
        :hostname => "ansible-server",
        :box => "centos/7",
        :ip => "172.28.128.10"
      },
      {
        :hostname => "node1",
        :box => "centos/7",
        :ip => "172.28.128.11"  
      },
      {
        :hostname => "node2",
        :box => "centos/7",
        :ip => "172.28.128.12"  
      }
    ]

Vagrant.configure("2") do |config|
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.network "private_network", ip: machine[:ip]
            node.vm.hostname = machine[:hostname]
        end
    end
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/setup.yml"
    end
end
