- hosts: all 
  become: true
  tasks:
  - name: setup ansible user
    user:
      name: ansible
    when: ansible_hostname != "ansible-server"

  - name: setup ansible user
    user:
      name: ansible
      generate_ssh_key: yes
    when: ansible_hostname == "ansible-server"

  - name: install Ansible
    yum:
      name: ansible
      state: latest
    when: ansible_hostname == "ansible-server"

  - name: disable host_key_checking
    lineinfile:
      path: /etc/ansible/ansible.cfg
      regexp: host_key_checking
      line: 'host_key_checking = False'
    when: ansible_hostname == "ansible-server" 

  - name: download public key from ansible-server to host machine
    fetch:
      src: /home/ansible/.ssh/id_rsa.pub
      dest: pub_key
    when: ansible_hostname == "ansible-server"

  - name: copy authorized_key
    authorized_key:
      user: ansible
      state: present
      key: "{{ lookup('file', 'pub_key/ansible-server/home/ansible/.ssh/id_rsa.pub') }}"
    when: ansible_hostname != "ansible-server"

  - name: add vms to /etc/hosts
    blockinfile:
      path: /etc/hosts
      block: |
        172.28.128.10 ansible-server   
        172.28.128.11 node1 
        172.28.128.12 node2 
      marker: "# {mark} ANSIBLE MANAGED BLOCK"

#  - name: remove temporary pub key (cleanup task, run last)
#    become: false
#    local_action: 
#      module: file 
#      path: pub_key 
#      state: absent
